"""Backend/provider contracts. No vendor SDKs or runtime execution."""
from dataclasses import dataclass
from typing import Protocol
from .ir import AcceleratorProgram, AcceleratorTarget
@dataclass(frozen=True)
class BackendArtifact: kind:str; target:str; payload:bytes; digest:str
class AcceleratorBackend(Protocol):
    target:AcceleratorTarget
    def compile(self, program:AcceleratorProgram)->BackendArtifact: ...
class AcceleratorProvider(Protocol):
    def discover_devices(self)->tuple[str,...]: ...
    def capabilities(self,device:str): ...
    def compile(self,program:AcceleratorProgram,target:AcceleratorTarget)->BackendArtifact: ...
    def allocate(self,*args,**kwargs): ...
    def upload(self,*args,**kwargs): ...
    def launch(self,*args,**kwargs): ...
    def download(self,*args,**kwargs): ...
    def synchronize(self,*args,**kwargs): ...
class SpirvBackend(Protocol): pass
class PtxBackend(Protocol): pass
class HipBackend(Protocol): pass
